=== krakhee20/jbit/JMSConnector/requirement/Schemas/XMLs/XSDs/SubscribeMessageRequestResponseSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="subscribeMessageRequest" type="subscribeMessageRequest"/> 
    <xs:complexType name="subscribeMessageRequest">
        <xs:sequence>
            <xs:element name="subscribeMessageActivityMetadata" type="typSubscribeMessageActivityMetadata"/>
        </xs:sequence>
    </xs:complexType>
    
	<xs:element name="subscribeMessageResponse" type="subscribeMessageResponse"/> 
    <xs:complexType name="subscribeMessageResponse">
        <xs:sequence>
            <xs:element name="Message" type="typMessage"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typSubscribeMessageActivityMetadata" >
        <xs:sequence>
            <xs:element name="TopicName" type="xs:string"/>
            <xs:element name="Durable" type="xs:boolean"/>
            <xs:element name="ClientID" type="xs:string"/>
            <xs:element name="DurableSubscriptionName" type="xs:string"/>
            <xs:element name="MessageType" type="xs:string"/>
            <xs:element name="MessageSelector" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    

    <xs:complexType name="typMessageHeaders" >
        <xs:sequence>
            <xs:element name="JMSCorrelationID" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSDeliveryMode" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSDestination" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSExpiration" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSMessageID" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSPriority" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSRedelivered" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSReplyTo" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSTimestamp" type="xs:string" minOccurs="1"/>
            <xs:element name="JMSType" type="xs:string" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typMessageProperty">
    	<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="value" type="xs:string" />
		</xs:sequence>		
    </xs:complexType>
    
    <xs:complexType name="typMessagePropertyList">
    	<xs:sequence>
        	<xs:element  name="MessageProperty" type="typMessageProperty" minOccurs="1" maxOccurs="unbounded">
	        </xs:element>
		</xs:sequence>	        
    </xs:complexType>
    
    <xs:complexType name="typMessage" >
        <xs:sequence>
            <xs:element name="MessageHeaders" type="typMessageHeaders"/>
            <xs:element name="MessageProperties" type="typMessagePropertyList" />
            <xs:element name="MessageBody" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== krakhee20/jbit/JMSConnector/requirement/Schemas/XMLs/SubscribeMessageResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<subscribeMessageResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SubscribeMessageRequestResponseSchema.xsd">
  <Message>
    <MessageHeaders>
      <JMSCorrelationID>JMSCorrelationID</JMSCorrelationID>
      <JMSDeliveryMode>JMSDeliveryMode</JMSDeliveryMode>
      <JMSDestination>JMSDestination</JMSDestination>
      <JMSExpiration>JMSExpiration</JMSExpiration>
      <JMSMessageID>JMSMessageID</JMSMessageID>
      <JMSPriority>JMSPriority</JMSPriority>
      <JMSRedelivered>JMSRedelivered</JMSRedelivered>
      <JMSReplyTo>JMSReplyTo</JMSReplyTo>
      <JMSTimestamp>JMSTimestamp</JMSTimestamp>
      <JMSType>JMSType</JMSType>
    </MessageHeaders>
    <MessageProperties>
      <MessageProperty>
        <name>name</name>
        <value>value</value>
      </MessageProperty>
    </MessageProperties>
    <MessageBody>MessageBody</MessageBody>
  </Message>
</subscribeMessageResponse>

=== krakhee20/jbit/JMSConnector/requirement/Schemas/XMLs/SubscribeMessageRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<subscribeMessageRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDs/SubscribeMessageRequestResponseSchema.xsd">
  <subscribeMessageActivityMetadata>
    <TopicName>TopicName</TopicName>
    <Durable>true</Durable>
    <ClientID>ClientID</ClientID>
    <DurableSubscriptionName>DurableSubscriptionName</DurableSubscriptionName>
    <MessageType>MessageType</MessageType>
    <MessageSelector>MessageSelector</MessageSelector>
  </subscribeMessageActivityMetadata>
</subscribeMessageRequest>
